defaults:
  - _datasets
  - _models
  - _self_

# -----------------------------------------------------------------
# ---                 Primary Run Configuration                 ---
# -----------------------------------------------------------------

# Select the active dataset and model for this test run.
active_dataset: OC_DATASET_2      # Options: PhotoMOCI, OC_DATASET_2
active_model_type: stablediffusion_text_img    # Options: ac_gan, gan_text, stablediffusion_text, stablediffusion_text_img, traditional_augmentation 


# If testing StyleGAN3, specify the variant.
stylegan_type: standard # Options: standard, ac_gan

# Path to pre-generated synthetic images for comparison metrics (e.g., FID).
generated_images_path: "D:/Tesi/FINAL_MODELS/synthetic_data/${active_dataset}/${active_model_type}"

# -----------------------------------------------------------------
# ---               Output & Evaluation Settings                ---
# -----------------------------------------------------------------

# Dataset splits to evaluate.
dataset_splits: ['test'] # Options: ['val'], ['test'], ['val', 'test']

batch_size: 32
num_workers: 5

# -----------------------------------------------------------------
# ---                 Model-Specific Parameters                 ---
# -----------------------------------------------------------------

# Parameters for LoRA Diffusion models.
diffusion_params:
  diffusion_steps: 100
  guidance_scale: 7.5
  diffusion_mode: img_to_img # Options: 'img_to_img', 'text_to_img'
  injection_lambda: null

# Parameters for StyleGAN3 models.
stylegan3_params:
  truncation_psi: 0.7
  noise_mode: 'const'
  translate: null
  rotate: null
  stylegan3_project_path: libs/stylegan3

# Prompts for calculating CLIP Score, keyed by class name.
clip_prompts_by_class:
  "aphthous": "a medical photograph of an aphthous lesion"
  "traumatic": "a medical photograph of a traumatic lesion"
  "neoplastic": "a medical photograph of a neoplastic lesion"
  "cancer": "a medical photograph of a cancerous tissue"
  "non cancer": "a medical photograph of healthy tissue"

# -----------------------------------------------------------------
# ---                  Compute & Hydra Settings                   ---
# -----------------------------------------------------------------

devices: 1

hydra:
  run:
    dir: "logs/test/${active_model_type}/${active_dataset}/${now:%Y-%m-%d_%H-%M-%S}"